spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}.userservice.svc.cluster.local:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      connect-timeout: 3000ms
      client-name: my-redis-app
      pool:
        enabled: true
        max-active: 8
        min-idle: 2
        max-wait: 1000ms

management:
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
        liveness:
          include: "*"
  endpoints:
    web:
      exposure:
        include: "health"
      base-path: "/actuator"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
