spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # ??? ?? create, create-drop, validate ??? ?? ??
    show-sql: true  # SQL ??? ??? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
